name: Publish to Forge
on:
  workflow_dispatch:

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - name: Clone mymodule
        uses: actions/checkout@v3
      - name: Clone modulerepo
        uses: actions/checkout@v3
        with:
          repository: nwolfe/modulerepo
          ref: main
          path: modulerepo
      - name: Prepare Build
        run: |
          echo .git/ > .pdkignore
          echo .pdkignore >> .pdkignore
      - name: Build Module
        uses: docker://puppet/pdk:latest
        with:
          args: 'build --force'
      - name: List Tarball
        run: tar -tf pkg/*
#      - name: Upload To Forge
#        uses: docker://puppet/pdk:latest
#        with:
#          args: 'release publish --force --forge-token ${{ secrets.PDK_FORGE_TOKEN }}'
