name: Publish to Forge
on:
  workflow_dispatch:

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - name: Clone repo
        uses: actions/checkout@v3
      - name: Build
        uses: docker://puppet/pdk:latest
        with:
          args: 'build --force'
      - name: Publish
        uses: docker://puppet/pdk:latest
        with:
          args: 'release publish --force --forge-token ${{ secrets.PDK_FORGE_TOKEN }}'
