name: Publish to Forge
on:
  workflow_dispatch:

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - name: Clone repo
        uses: actions/checkout@v3
      - name: Install Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: '2.7'
          bundler-cache: true
      - name: Build
        run: bundle exec pdk build --force
      - name: Publish
        env:
          PDK_FORGE_TOKEN: ${{ secrets.PDK_FORGE_TOKEN }}
        run: bundle exec pdk release publish --force
