name: Update Component

on:
  workflow_dispatch:
    inputs:
      image_ref:
        type: string
        required: true
        description: Foo
      app:
        type: string
        required: true
        description: Bar
  workflow_call:
    inputs:
      image_ref:
        type: string
        required: true
        description: Foo
      app:
        type: string
        required: true
        description: Bar

jobs:
  update:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - run: git status
      - run: echo ${{ inputs.app }} ${{ inputs.image_ref }}
